// This is the only include you need
#include "DirectFormI.h"

#include <sstream>
#include <iostream>
#include <iomanip>
#include <stdio.h>
#include <assert.h>

// Notch filter, 2nd order bandstop which means 2 biquad filters
// 50Hz notch frequency, sampling rate 1kHz
//
// generated by the Python script gen_coeff
// [ 15672. -29825.  15672.  16384. -30222.  15624.]
// [ 16384. -31180.  16384.  16384. -30753.  15720.]

int main (int,char**)
{
	// scale coefficients by 2^14 so that we max out the dynamic
	// range of short int
	int q = 14;
	DirectFormI biquad1(15672,-29825,15672,16384,-30222,15624,14);
	DirectFormI biquad2(16384,-31180,16384,16384,-30753,15720,14);
	
	FILE *finput = fopen("ecg2.dat","rt");
	assert(finput != NULL);
	FILE *foutput = fopen("ecg2_filtered.dat","wt");
	assert(foutput != NULL);
	for(;;) 
	{
		// the data file has 3 channels and time
		short x1,x2,x3,y;
		int t;
		if (fscanf(finput,"%d %hd %hd %hd\n",&t,&x1,&x2,&x3)<1) break;
		y = biquad1.filter(x2);
		y = biquad2.filter(y);
		fprintf(foutput,"%d %hd\n",t,y);
	}
	fclose(finput);
	fclose(foutput);
	fprintf(stderr,"Written the filtered ECG to 'ecg_filtered.dat'\n");
}
